# Generated by Django 3.2.9 on 2021-11-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='writer',
            name='id',
            field=models.CharField(max_length=27, primary_key=True, serialize=False),
        ),
    ]
