# Generated by Django 3.2.9 on 2021-11-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20211114_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
