version: '3.3'
   
services:
   backend_lomex:
    build: backend
    command: sh ./run.sh
    volumes:
      - ./backend:/srv/project
    ports:
      - "8081:8081"
   frontend_lomex:
    build: frontend
    container_name: frontend_lomex
    restart: always
    command: sh ./run.sh
    depends_on:
     - backend_lomex
    ports:
     - "8080:8080"
        
